language: ruby

rvm:
  - 2.1

gemfile:
  - gemfiles/rails_3.0.5.gemfile
  - gemfiles/rails_3.0.6.gemfile
  - gemfiles/rails_3.0.7.gemfile
  - gemfiles/rails_3.0.8.gemfile
  - gemfiles/rails_3.0.9.gemfile
  - gemfiles/rails_3.0.10.gemfile
  - gemfiles/rails_3.0.11.gemfile
  - gemfiles/rails_3.0.12.gemfile
  - gemfiles/rails_3.0.13.gemfile
  - gemfiles/rails_3.0.14.gemfile
  - gemfiles/rails_3.0.15.gemfile
  - gemfiles/rails_3.0.16.gemfile
  - gemfiles/rails_3.0.17.gemfile
  - gemfiles/rails_3.0.18.gemfile
  - gemfiles/rails_3.0.19.gemfile
  - gemfiles/rails_3.0.20.gemfile
  - gemfiles/rails_3.1.0.gemfile
  - gemfiles/rails_3.1.2.gemfile
  - gemfiles/rails_3.1.3.gemfile
  - gemfiles/rails_3.1.4.gemfile
  - gemfiles/rails_3.1.5.gemfile
  - gemfiles/rails_3.1.6.gemfile
  - gemfiles/rails_3.1.7.gemfile
  - gemfiles/rails_3.1.8.gemfile
  - gemfiles/rails_3.1.9.gemfile
  - gemfiles/rails_3.1.10.gemfile
  - gemfiles/rails_3.1.11.gemfile
  - gemfiles/rails_3.1.12.gemfile
  - gemfiles/rails_3.2.0.gemfile
  - gemfiles/rails_3.2.1.gemfile
  - gemfiles/rails_3.2.2.gemfile
  - gemfiles/rails_3.2.3.gemfile
  - gemfiles/rails_3.2.4.gemfile
  - gemfiles/rails_3.2.5.gemfile
  - gemfiles/rails_3.2.6.gemfile
  - gemfiles/rails_3.2.7.gemfile
  - gemfiles/rails_3.2.8.gemfile
  - gemfiles/rails_3.2.9.gemfile
  - gemfiles/rails_3.2.10.gemfile
  - gemfiles/rails_3.2.11.gemfile
  - gemfiles/rails_3.2.12.gemfile
  - gemfiles/rails_3.2.13.gemfile
  - gemfiles/rails_3.2.14.gemfile
  - gemfiles/rails_3.2.15.gemfile
  - gemfiles/rails_3.2.16.gemfile
  - gemfiles/rails_3.2.17.gemfile
  - gemfiles/rails_3.2.18.gemfile
  - gemfiles/rails_3.2.19.gemfile
  - gemfiles/rails_3.2.20.gemfile
  - gemfiles/rails_3.2.21.gemfile
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.0.1.gemfile
  - gemfiles/rails_4.0.2.gemfile
  - gemfiles/rails_4.0.3.gemfile
  - gemfiles/rails_4.0.4.gemfile
  - gemfiles/rails_4.0.5.gemfile
  - gemfiles/rails_4.0.6.gemfile
  - gemfiles/rails_4.0.7.gemfile
  - gemfiles/rails_4.0.8.gemfile
  - gemfiles/rails_4.0.9.gemfile
  - gemfiles/rails_4.0.10.gemfile
  - gemfiles/rails_4.0.11.gemfile
  - gemfiles/rails_4.0.11.1.gemfile
  - gemfiles/rails_4.0.12.gemfile
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.1.1.gemfile
  - gemfiles/rails_4.1.2.gemfile
  - gemfiles/rails_4.1.3.gemfile
  - gemfiles/rails_4.1.4.gemfile
  - gemfiles/rails_4.1.5.gemfile
  - gemfiles/rails_4.1.6.gemfile
  - gemfiles/rails_4.1.7.gemfile
  - gemfiles/rails_4.1.7.1.gemfile
  - gemfiles/rails_4.1.8.gemfile
  - gemfiles/rails_4.1.9.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_4.2.1.gemfile
  - gemfiles/rails_4.2.3.gemfile

sudo: false
